//! Types for libinput configuration.

/// Pointer acceleration profile
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AccelProfile {
    /// A flat acceleration profile.
    ///
    /// Pointer motion is accelerated by a constant (device-specific) factor, depending on the current speed.
    Flat = 1,
    /// An adaptive acceleration profile.
    ///
    /// Pointer acceleration depends on the input speed. This is the default profile for most devices.
    Adaptive,
}

/// The click method defines when to generate software-emulated buttons, usually on a device
/// that does not have a specific physical button available.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ClickMethod {
    /// Use software-button areas to generate button events.
    ButtonAreas = 1,
    /// The number of fingers decides which button press to generate.
    Clickfinger,
}

/// The scroll method of a device selects when to generate scroll axis events instead of pointer motion events.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ScrollMethod {
    /// Never send scroll events instead of pointer motion events.
    ///
    /// This has no effect on events generated by scroll wheels.
    NoScroll = 1,
    /// Send scroll events when two fingers are logically down on the device.
    TwoFinger,
    /// Send scroll events when a finger moves along the bottom or right edge of a device.
    Edge,
    /// Send scroll events when a button is down and the device moves along a scroll-capable axis.
    OnButtonDown,
}

/// Map 1/2/3 finger tips to buttons.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TapButtonMap {
    /// 1/2/3 finger tap maps to left/right/middle
    LeftRightMiddle,
    /// 1/2/3 finger tap maps to left/middle/right
    LeftMiddleRight,
}

/// Possible settings for libinput.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum LibinputSetting {
    /// Set the pointer acceleration profile
    AccelProfile(AccelProfile),
    /// Set pointer acceleration speed
    AccelSpeed(f64),
    /// Set the calibration matrix
    CalibrationMatrix([f32; 6]),
    /// Set the [`ClickMethod`]
    ClickMethod(ClickMethod),
    /// Set whether the device gets disabled while typing
    DisableWhileTyping(bool),
    /// Set left handed mode
    LeftHanded(bool),
    /// Allow or disallow middle mouse button emulation
    MiddleEmulation(bool),
    /// Set the rotation angle
    RotationAngle(u32),
    /// Set the scroll button
    ScrollButton(u32),
    /// Set whether the scroll button should be a drag or toggle
    ScrollButtonLock(bool),
    /// Set the [`ScrollMethod`]
    ScrollMethod(ScrollMethod),
    /// Enable or disable natural scrolling
    NaturalScroll(bool),
    /// Set the [`TapButtonMap`]
    TapButtonMap(TapButtonMap),
    /// Enable or disable tap-to-drag
    TapDrag(bool),
    /// Enable or disable a timeout where lifting a finger off the device will not stop dragging
    TapDragLock(bool),
    /// Enable or disable tap-to-click
    Tap(bool),
}
